### PR TITLE
Update many-rs dependencies

### PR DESCRIPTION
**Pull request by hansl**

### CODE REVIEW

**Comment by fmorency** [comment]
LGTM but right now the CICD of `many-rs` fails because of `fmt`.

@brohamgoham can you fix `many-rs` using `cargo fmt`?

@hansl there should be a way to disable merging capabilities if CICD fails.

See https://github.com/l-1-labs/many-rs/actions/runs/2035414917

**Review by fmorency — CHANGES_REQUESTED** [review]
Fix `many-rs` first, then update this PR to point to the correct rev.

**Comment by brohamgoham** [comment]
> Fix `many-rs` first, then update this PR to point to the correct rev.

Fixed ci fail with cargo fmt, should be OK now @fmorency

**Comment by fmorency** [comment]
@brohamgoham you now need to update the `many-rs` hash to `4b642446c83cc5d541773fdd2c343733c803900b`

**Review by brohamgoham — APPROVED** [review]

**Pull request merged**
